### PR TITLE
Follow up on WebSocket connection support

### LINKED ISSUE #365: Use `doc_cfg` (`#[doc(cfg(feature = "..."))]`) to show feature requirements
Show these in docs for `derive` and `ws`:
image

`![feature(doc_cfg)]` is nightly only, but `docs.rs` uses nightly by default.

From https://stackoverflow.com/a/61417700

```toml
# docs.rs-specific configuration
[package.metadata.docs.rs]
# document all features
all-features = true
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
```
```rust
// only enables the `doc_cfg` feature when
// the `docsrs` configuration attribute is defined
#[cfg_attr(docsrs, feature(doc_cfg))]

#[cfg_attr(docsrs, doc(cfg(feature = "macros")))]
pub fn test() {}
```

### LINKED ISSUE #369: websocket connections can panic based on connection errors
https://github.com/clux/kube-rs/blob/e4d999b361ae59c6755205658bf4c8638595c616/kube/src/client/mod.rs#L156-L160

For example, async-tungstenite in rustls mode will convert TLS errors into `ws2::Error::Io` (since `ws2::Error::Tls` is only available in native TLS mode), which would cause a panic.

https://github.com/sdroege/async-tungstenite/blob/33e3722ab0931551128887e6ed6b2af78498427a/src/tokio/rustls.rs#L44-L49

I'd also assume that basic stuff like "no route to host" or "connection refused" would be IO errors (and thus also panic).

I'm also a bit wary of the general policy of a catch-all panic case, which would bite us hard if they ever decide to split up any error cases (for example).

### PR DESCRIPTION
**Pull request by kazk**
- Use re-exported `native_tls`
- Support `config.accept_invalid_certs` with `ws-rustls-tls`
- Run `ws` tests on Circle CI (mostly to make sure it compiles on both TLS)
- Remove catch all panic from WS connect
- Use `doc_cfg` on docs.rs (closes #365)
    - To try: `cargo +nightly rustdoc --lib --features=derive,ws,ws-native-tls -- --cfg docsrs`
- Fix broken links in docs
- Avoid panicking on connection failure (closes #369)

### CODE REVIEW

File: kube/src/client/mod.rs [hunk 1]
```diff
@@ -130,35 +130,48 @@ impl Client {
...
+                // Protocol errors:
+                // - Only GET is supported
+                // - Only HTTP version >= 1.1 is supported
+                // shouldn't happen in our case
+                ws2::Error::Protocol(msg) => Err(Error::RequestValidation(msg.into())),
+
+                // `tungstenite` docs says that `Error::Io` should probably be considered fatal.
+                // However, `async-tungstenite` seems to use it for some recoverable errors we don't want to panic.
+                // TODO Figure out how to extract those cases or fix upstream. See https://github.com/clux/kube-rs/issues/369
+                ws2::Error::Io(err) => panic!("WebSocket connection error: {}", err),
```
Comment (kazk) [inline kube/src/client/mod.rs:164]: `err` is `std::io::Error`.
`err.get_ref()` (reference to the inner error) is `Option<&(dyn error::Error + Send + Sync + 'static)>`.

We can at least match `io::ErrorKind::InvalidInput` case from `TcpStream::connect`. Others with `io::ErrorKind::Other` are painful.

File: kube/src/client/mod.rs [hunk 2]
```diff
@@ -130,35 +131,60 @@ impl Client {
...
+                    | std::io::ErrorKind::Interrupted
+                    | std::io::ErrorKind::InvalidInput
+                    | std::io::ErrorKind::InvalidData
+                    | std::io::ErrorKind::NotConnected
+                    | std::io::ErrorKind::NotFound
+                    | std::io::ErrorKind::TimedOut
+                    | std::io::ErrorKind::UnexpectedEof
+                    | std::io::ErrorKind::WouldBlock => Err(Error::Connection(err)),
+
+                    _ => panic!("WebSocket connection error: {}", err),
```
Comment (kazk) [inline kube/src/client/mod.rs:176]: For other stuff, I think we'll need to match with `std::io::ErrorKind::Other` and stringify the error, then test if the string contains errors we'd like to avoid panic...

Comment (clux) [reply kube/src/client/mod.rs:176]: Could we not just put all the io errors into `Error::Connection`? I feel `panic!` is the wrong default for error cases we didn't cover.

File: kube/src/client/mod.rs [hunk 3]
```diff
@@ -130,35 +131,60 @@ impl Client {
...
+                },
+
+                // Unexpected errors. `tungstenite::Error` contains errors that doesn't happen when trying to conect.
+                ws2::Error::ConnectionClosed
+                | ws2::Error::AlreadyClosed
+                | ws2::Error::Utf8
+                | ws2::Error::Capacity(_)
+                | ws2::Error::SendQueueFull(_) => {
+                    panic!("Unexpected {}", err);
```
Comment (clux) [inline kube/src/client/mod.rs:185]: This is also probably not worthy of a `panic!`. If the call to `attach/exec` is part of a webapp, then sure, that part won't work, but we won't need to take down the entire app.

File: kube/Cargo.toml [hunk 4]
```diff
@@ -23,11 +23,13 @@ derive = ["kube-derive"]
 ws = ["async-tungstenite", "tokio-util"]
 # We can merge these with `native-tls`/`rustls-tls` when `dep?/feature` syntax becomes stable.
 # https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#weak-dependency-features
-ws-native-tls = ["real-native-tls", "tokio-native-tls", "async-tungstenite/tokio-native-tls"]
+ws-native-tls = ["tokio-native-tls", "async-tungstenite/tokio-native-tls"]
 ws-rustls-tls = ["tokio-rustls", "async-tungstenite/tokio-rustls"]
 
 [package.metadata.docs.rs]
 features = ["derive", "ws", "ws-native-tls"]
+# Define the configuration attribute `docsrs`. Used to enable `doc_cfg` feature.
```
Comment (clux) [inline kube/Cargo.toml:31]: ah, nice!

File: kube/src/client/mod.rs (hunk 2 above)
Comment (kazk) [reply kube/src/client/mod.rs:176]: Sure, that's easy :)

**Review by clux — APPROVED** [review]
comment on panics, but everything else looks great!

File: kube/src/client/mod.rs (hunk 3 above)
Comment (kazk) [reply kube/src/client/mod.rs:170]: These should never happen *when trying to connect* unless I'm misunderstanding. So there's something seriously wrong if it does.

- `ConnectionClosed` comes after `close` handshake which must be after the initial handshake (this connection) by definition.
- `AlreadyClosed` is even after that because it only happens if you tried to read/write on closed connection.
- `Utf8` is for receiving invalid text fame (I think)
- `Capacity` is about the message being too big
- `SendQueueFull` is about the message queue being full

If not panicking, should there be some generic error variant for those "totally unexpected, but probably not panic worthy" error?

Comment (clux) [reply kube/src/client/mod.rs:170]: Ah, during connect. Yeah, I mean this is fine in the sense that we feel we "know it cannot happen", and we are explicit about it. However, it's not an __unrecoverable error__ for a larger application, which is what `panic!` is for.

If some part of a larger app tries to use kube ws features in some subroutine and it fails, it's fine to return an error type covering totally unexpected parts. Nothing bad will happen as a consequence (other than that part failing to work), it'll propagate up to whomever wants to handle it (or main).

Comment (clux) [reply kube/src/client/mod.rs:170]: I guess the annoying thing is that we are splitting up `ws::Error` for user ergonomics and partitioning them into `kube::Error` types (which historically has just re-exported libraries' error types verbatim).

I think some kind of `WsOther` error which stringifies the remaining cases is probably good enough if we have a comment of the ones we expect in there.

Comment (kazk) [reply kube/src/client/mod.rs:170]: (I honestly think `tungstenite` should provide better error type that describes possible errors during connect, so that users like us don't need to guess and decide.)

I used `panic!` here because, to me, this is a broken contract and **is** unrecoverable. It's similar to when we use `.expect`. If the code reaches here, there _might_ be something truly wrong, and I'd rather have my larger app fail when this happens than to have an ambiguous error variant that is returned for unknown reason. No one knows what's safe anymore at this point.

> `panic!` is often appropriate if you’re calling external code that is out of your control and it returns an invalid state that you have no way of fixing.
>
> https://doc.rust-lang.org/book/ch09-03-to-panic-or-not-to-panic.html#guidelines-for-error-handling

> Nothing bad will happen as a consequence (other than that part failing to work)

I guess we just disagree here. I just have a more pessimistic view and can't say this :laughing:

I don't have a strong opinion. Especially because I doubt the code will ever reach here. If we're returning Err instead, what should I use?

Comment (kazk) [reply kube/src/client/mod.rs:170]: Sorry, I somehow didn't get your second comment until now. So my reply is just based on your first one.

Comment (kazk) [reply kube/src/client/mod.rs]: Added `WsOther`

**Comment by kazk** [comment]
Should be ready for merge.

File: kube/src/client/mod.rs (hunk 3 above)
Comment (clux) [reply kube/src/client/mod.rs]: Hm.. Yeah, I understand the concern there. It would be a broken contract for the `connect` function to see, and it would probably cause further failures down the line for any continued calls to ws features (probably spamming continued errors in the logs of a larger application).

I can see a point for having that last `panic!` there. We would probably catch it early (since it's early stages of app functionality, after which it's possible nothing related to ws would work if it failed), it would indicate a bug in tungstenite, which could indicate a broken state, and maybe tungstenite is scribbling over memory as a result of that, but that feels like speculation to me. If it's possible however; that tungstenite can recover (through another connect say), so I am generally in favour of letting the app try (even if it's not great for it).

Still, this does feel like a bit of a philosophical point. Like in a normal k8s deployment setting, do we want:
1. degraded performance of pod(s) (where we potentially have lots of duplicate error logs, and non-working features within)
2. fully working pods, but with frequent crashes if something surfaces (potentially leading to full downtime if all replicas have frequent restarts on the same issue)

neither is great, and the choice is only for that time between it happening and when it's fixed.
2 is great when developing fast, but in a cloud with good observability or when working with inherited code (coding defensively); it's nice not causing outages on huge monoliths with http route or something. But that forces you to make the delineation of what's crucial enough to take down the app early if nothing panics (which usually leads to a period of spamming errors first).

Still, am on the fence about this particular one. panic is inflexible because it will cause downtime if we got it wrong (and propagated a panic in a legit recoverable case), but what they are doing IS wrong. If you are happy with that, I don't mind the panic really.

**Comment by clux** [comment]
Thanks! Looks great.
Left one last comment on the `panic!`, I am happy to backtrack on it if you still feel strongly about it.
But otherwise I'll merge it later on tonight.

**Comment by jbg** [comment]
I'm hitting a build error in this branch when using it as a dependency.

There seems to be an undeclared dependency on the `io` feature of `tokio-util` being enabled. I get this build error:

```
error[E0433]: failed to resolve: could not find `io` in `tokio_util`
   --> /cargo/git/checkouts/kube-rs-97ea51fe938f4d16/ed3f44d/kube/src/api/remote_command.rs:173:40
    |
173 |     let mut stdin_stream = tokio_util::io::ReaderStream::new(stdin);
    |                                        ^^ could not find `io` in `tokio_util`
```

... which is resolved by adding a dependency `tokio-util = { version = "0.6", features = ["io"] }` to my crate - kube should add the feature to its dependency.

**Comment by kazk** [comment]
@clux I think it's fine to have `WsOther` for now. Both `WsOther` and `panic!` on unexpected `tungstenite::Error` variant are hacks. Ideally, `tungstenite` should have a set of _possible_ errors, so we know exactly what to expect and don't have to propagate this confusion to our users, but it doesn't. Returning `WsOther` will give our users a choice to ignore or panic depending on their need.

@jbg Thanks for letting us know. Fixed it.
